### ISSUE TITLE
Bye-bye boilerplate - use Lambok where necessary

### ISSUE THREAD

**Issue by michaelharlow** [ucmo-cs/F24_Avengers#14]
### Lambok is included as a dependency on project - we should use it

The annotion `@getter` can be added to data classes to replace getter method boiler plate

### Example
**Bad:**
```Java
public class Login {
    private String username;
    private String password;

    String getUsername() {
        return this.username;
    }

    String getPassword() {
        return this.password;
    }
}
```
 **Good: it auto generates getters** 
```Java
@Getter
public class Login {
    private String username;
    private String password;
}
```

**Comment by SreejaMandla** [comment]
can i have this issue assigned?

**Comment by ErskineTurnerDWMG** [comment]
Pull request submitted.  Please let  me know if there's any changes needed.
