### ISSUE TITLE
IDs should be generated by Jakarta Persistence

### ISSUE THREAD

**Issue by michaelharlow** [ucmo-cs/F24_Avengers#4]
The ID fields in both the [Account.java](https://github.com/ucmo-cs/F24_Avengers/blob/6fa2d9bdd58457c7de488b23b1f65fd53980b38f/src/main/java/com/avengers/example/domain/Account.java#L11-L12) and [Loan.java](https://github.com/ucmo-cs/F24_Avengers/blob/6fa2d9bdd58457c7de488b23b1f65fd53980b38f/src/main/java/com/avengers/example/domain/Loan.java#L11-L12) should be changed to be automatically generated when created in the database.

```Java 
@GeneratedValue(strategy = GeneratedType.IDENTITY) //This will auto assign an incrementing ID to new instances
```

Additionally the constructors need to remove the ID fields as the api will never specify the ID, since it is autogenerated.

**Comment by Hemachandra6** [comment]
Hi @michaelharlow. I would like to work on this issue.
